version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql               # Persistent volume for MySQL data
      - ./db-init:/docker-entrypoint-initdb.d    # Initial SQL scripts directory

  web:
    build: .
    working_dir: /app                            # Set working directory to /app in the container
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app                                   # Mounts the current directory to /app in the container
    command: ["python", "app.py"]                # Command to run the Flask app

volumes:
  mysql-data:                                    # Declares the named volume for MySQL data persistence
