version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: media_tracker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql               # Persistent volume for MySQL data
      - ./db-init:/docker-entrypoint-initdb.d    # Initial SQL scripts directory

  web:
    build: .
    working_dir: /app                            # Set working directory to /app in the container
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: media_tracker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql1234
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app                                   # Mounts the current directory to /app in the container
    command: ["python", "app.py"]                # Command to run the Flask app
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:
  jenkins_home:                                    # Declares the named volume for MySQL data persistence
